# .github/workflows/test.yml
name: Run Tests

on:
  push:
    branches: [ main, develop ]  # Run on push to these branches
  pull_request:
    branches: [ main ]          # Run on PRs to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 🔹 1. Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 🔹 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 🔹 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 🔹 4. Run pytest
      - name: Run pytest
        run: |
          pytest tests/core/test_hybrid_rag_router.py -v

      # 🔹 Optional: Show coverage
      # - name: Install and run coverage
      #   run: |
      #     pip install pytest-cov
      #     pytest --cov=app tests/core/test_hybrid_rag_router.py
